name: all_in_one_tool
description: "Tất cả các tiện ích cá nhân sử dụng hằng ngày - AllinOne Tools"
publish_to: 'none'

version: 3.1.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  intl: ^0.18.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_speed_dial: ^7.0.0

  image: ^4.0.17
  image_picker: ^1.0.0
  video_player: ^2.7.0
  chewie: ^1.7.4
  flutter_image_compress: ^2.1.0

  path: ^1.9.0
  path_provider: ^2.0.14

  permission_handler: ^12.0.1

  mobile_scanner: ^7.0.1

  crypto: ^3.0.6
  encrypt: ^5.0.3

  math_expressions: ^3.0.0
  random_string: ^2.3.1
  flutter_animate: ^4.5.2

  lottie: ^3.3.1

  dropdown_search: ^5.0.6
  full_calender: ^1.2.12
  lunar_calendar_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

